apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"hello-world-argocd-application","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"helm-example","app.kubernetes.io/version":"2.0.0","helm.sh/chart":"helm-example-0.1.0"},"name":"hello-world-argocd-application-helm-example","namespace":"hello-world-app"},"spec":{"replicas":1,"selector":{"matchLabels":{"app.kubernetes.io/instance":"hello-world-argocd-application","app.kubernetes.io/name":"helm-example"}},"template":{"metadata":{"labels":{"app.kubernetes.io/instance":"hello-world-argocd-application","app.kubernetes.io/name":"helm-example"}},"spec":{"containers":[{"image":"046709407808.dkr.ecr.eu-west-1.amazonaws.com/gitops-argocd:master-f097b61","imagePullPolicy":"IfNotPresent","livenessProbe":{"httpGet":{"path":"/","port":"http"}},"name":"helm-example","ports":[{"containerPort":80,"name":"http","protocol":"TCP"}],"readinessProbe":{"httpGet":{"path":"/","port":"http"}},"resources":{},"securityContext":{}}],"securityContext":{},"serviceAccountName":"default"}}}}
  creationTimestamp: "2023-04-12T13:35:33Z"
  generation: 2
  labels:
    app.kubernetes.io/instance: hello-world-argocd-application
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: helm-example
    app.kubernetes.io/version: 2.0.0
    helm.sh/chart: helm-example-0.1.0
  name: hello-world-argocd-application-helm-example
  namespace: hello-world-app
  resourceVersion: "60030"
  uid: 8a22a246-a450-4e39-90d9-f75999b9be1a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: hello-world-argocd-application
      app.kubernetes.io/name: helm-example
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: hello-world-argocd-application
        app.kubernetes.io/name: helm-example
    spec:
      containers:
      - image: 046709407808.dkr.ecr.eu-west-1.amazonaws.com/gitops-argocd:master-f097b61
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: helm-example
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-04-12T13:35:36Z"
    lastUpdateTime: "2023-04-12T13:35:36Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-04-12T13:35:33Z"
    lastUpdateTime: "2023-04-12T14:47:08Z"
    message: ReplicaSet "hello-world-argocd-application-helm-example-6dc5964d59" has
      successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
