apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: eks.privileged
  creationTimestamp: "2023-04-12T14:47:07Z"
  generateName: hello-world-argocd-application-helm-example-6dc5964d59-
  labels:
    app.kubernetes.io/instance: hello-world-argocd-application
    app.kubernetes.io/name: helm-example
    pod-template-hash: 6dc5964d59
  name: hello-world-argocd-application-helm-example-6dc5964d59-vtn4x
  namespace: hello-world-app
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: hello-world-argocd-application-helm-example-6dc5964d59
    uid: 77107704-cca2-43fc-ac35-5bd20462d546
  resourceVersion: "60015"
  uid: 14b87338-f10a-4fa2-8839-07ffe69fbfae
spec:
  containers:
  - image: 046709407808.dkr.ecr.eu-west-1.amazonaws.com/gitops-argocd:master-f097b61
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: http
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: helm-example
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: http
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    securityContext: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-lbr42
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ip-10-0-2-111.eu-west-1.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-lbr42
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-04-12T14:47:07Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-04-12T14:47:08Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-04-12T14:47:08Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-04-12T14:47:07Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://3e69bf39c4a2462c6b3c0c4a6c87183b70afffca8db6aed334e3a79bd657f598
    image: 046709407808.dkr.ecr.eu-west-1.amazonaws.com/gitops-argocd:master-f097b61
    imageID: 046709407808.dkr.ecr.eu-west-1.amazonaws.com/gitops-argocd@sha256:b06c6bc87c869204bc0e1b501897cadd6dcae207ec805aed662003e86626a309
    lastState: {}
    name: helm-example
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-04-12T14:47:08Z"
  hostIP: 10.0.2.111
  phase: Running
  podIP: 10.0.2.16
  podIPs:
  - ip: 10.0.2.16
  qosClass: BestEffort
  startTime: "2023-04-12T14:47:07Z"
